### ISSUE TITLE
E_ERROR - Uncaught Error: Call to undefined method WP_Post::getDate()

### ISSUE THREAD

**Issue by Phyks** [comptoirdesappli/amapress#17]
Bonjour,

J'ai récemment découvert amapress et souhaitait l'essayer pour mon AMAP. Lors de la création d'un contrat légumes, j'ai dû rater une étape (et possiblement ne pas définir les paniers / distributions) et obtient désormais une erreur :

```
Une erreur de type E_ERROR a été causée dans la ligne 97 du fichier /home/www/wordpress/wp-content/plugins/amapress/class.amapress.paniers.php. Message d’erreur : Uncaught Error: Call to undefined method WP_Post::getDate() in /home/www/wordpress/wp-content/plugins/amapress/class.amapress.paniers.php:97
Stack trace:
#0 /home/www/wordpress/wp-content/plugins/amapress/class.amapress.contrats.php(71): AmapressPaniers::generate_paniers(136, false, true)
#1 /home/www/wordpress/wp-content/plugins/amapress/class.amapress.contrats.php(50): AmapressContrats::get_contrat_status(136, false)
#2 /home/www/wordpress/wp-content/plugins/amapress/amapress.php(1423): AmapressContrats::get_contrat_to_generate()
#3 /home/www/wordpress/wp-includes/class-wp-hook.php(288): {closure}('')
#4 /home/www/wordpress/wp-includes/class-wp-hook.php(312): WP_Hook->apply_filters(NULL, Array)
#5 /home/www/wordpress/wp-includes/plugin.php(478): WP_Hook->do_action(Array)
#6 /home/www/wordpress/wp-admin/admin-ajax.php(45): do_action('admin_init')
#7 {main}
  thrown
```

systématiquement, à chaque fois que j'accède à l'interface Wordpress admin.

Comment pourrais-je régler ce problème (sans aller supprimer de force dans la base de données) ?

Merci,

**Comment by sharevb** [comment]
Bonsoir,

Merci pour ce retour.  Ce bug devrait être corrigé dans la version 0.91.15.

**Comment by Phyks** [comment]
Je confirme, merci pour cette correction très rapide !
